#!/usr/bin/env python3
"""
Generate sweep_params.txt from a parameter grid.

Usage:
    python generate_sweep_params.py

Customize the PARAM_GRID dictionary below to define your sweep.
"""

import itertools
from pathlib import Path

# ============================================================================
# PARAMETER GRID - Customize this!
# ============================================================================

PARAM_GRID = {
    'learning_rate': [0.001, 0.0005, 0.0001],
    'lambda_bc': [0.1, 0.01, 0.001],
    # 'batch_size': [500, 1000, 2000],
    # 'reliability_loss_scale': [10.0, 100.0, 1000.0],
    # 'dropout': [0.0, 0.1, 0.2],
    # 'weight_decay': [0.0, 0.001, 0.01],
}

# Fixed parameters (applied to all runs)
FIXED_PARAMS = {
    'epochs': 1500,
    # 'n_train': 10,
    # 'n_test': 5,
}

# ============================================================================

def generate_sweep_params(param_grid: dict, fixed_params: dict = None) -> list:
    """Generate all parameter combinations from a grid."""
    if fixed_params is None:
        fixed_params = {}

    # Get all parameter names and their values
    param_names = list(param_grid.keys())
    param_values = list(param_grid.values())

    # Generate all combinations
    combinations = []
    for values in itertools.product(*param_values):
        params = dict(zip(param_names, values))
        params.update(fixed_params)
        combinations.append(params)

    return combinations


def format_run_name(params: dict) -> str:
    """Create a descriptive run name from parameters."""
    parts = []
    for key, value in params.items():
        if key in ['epochs', 'patience']:
            continue  # Skip non-essential params in name
        if isinstance(value, float):
            if value >= 1:
                parts.append(f"{key}_{value:.0f}")
            elif value >= 0.01:
                parts.append(f"{key}_{value:.2f}".replace('.', 'p'))
            else:
                # Scientific notation for small values
                exp = f"{value:.0e}".replace('-0', '-').replace('+0', '')
                parts.append(f"{key}_{exp}")
        else:
            parts.append(f"{key}_{value}")
    return "_".join(parts)


def format_params_line(run_name: str, params: dict) -> str:
    """Format a single line for sweep_params.txt."""
    param_strs = [f"{k}={v}" for k, v in params.items()]
    return f"{run_name} " + " ".join(param_strs)


def main():
    output_file = Path(__file__).parent / "sweep_params.txt"

    combinations = generate_sweep_params(PARAM_GRID, FIXED_PARAMS)

    print(f"Generating {len(combinations)} parameter combinations...")

    lines = [
        "# Controller Parameter Sweep Configuration",
        "# Generated by generate_sweep_params.py",
        "#",
        f"# Total configurations: {len(combinations)}",
        f"# Grid: {PARAM_GRID}",
        f"# Fixed: {FIXED_PARAMS}",
        "#",
        f"# Update sweep.sh: --array=0-{len(combinations)-1}",
        "# =========================================",
        "",
    ]

    for params in combinations:
        run_name = format_run_name(params)
        line = format_params_line(run_name, params)
        lines.append(line)

    with open(output_file, 'w') as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written to: {output_file}")
    print(f"\nRemember to update sweep.sh:")
    print(f"  #SBATCH --array=0-{len(combinations)-1}")


if __name__ == '__main__':
    main()
