"""
Test script to verify controllable inputs logic without full dependencies.

NEW BEHAVIOR: Policy generators output ONLY controllable inputs, which are then
merged with non-controllable values from the target trajectory.
"""

# Simulated process configs
PROCESSES = [
    {
        'name': 'laser',
        'input_labels': ['PowerTarget', 'AmbientTemp'],
        'controllable_inputs': ['PowerTarget'],
    },
    {
        'name': 'plasma',
        'input_labels': ['RF_Power', 'Duration'],
        'controllable_inputs': ['RF_Power'],
    },
    {
        'name': 'galvanic',
        'input_labels': ['CurrentDensity', 'Duration'],
        'controllable_inputs': ['CurrentDensity', 'Duration'],
    },
    {
        'name': 'microetch',
        'input_labels': ['Temperature', 'Concentration', 'Duration'],
        'controllable_inputs': ['Concentration', 'Duration'],
    }
]

def get_controllable_info(process_config):
    """
    Get information about controllable and non-controllable inputs.

    This mirrors ProcessChain._get_controllable_info()
    """
    input_labels = process_config['input_labels']
    controllable = process_config.get('controllable_inputs', input_labels)

    controllable_indices = []
    non_controllable_indices = []
    controllable_labels = []
    non_controllable_labels = []

    for idx, label in enumerate(input_labels):
        if label in controllable:
            controllable_indices.append(idx)
            controllable_labels.append(label)
        else:
            non_controllable_indices.append(idx)
            non_controllable_labels.append(label)

    return {
        'controllable_indices': controllable_indices,
        'non_controllable_indices': non_controllable_indices,
        'controllable_labels': controllable_labels,
        'non_controllable_labels': non_controllable_labels,
        'n_controllable': len(controllable_indices),
        'n_non_controllable': len(non_controllable_indices),
    }


def simulate_merge_controllable_inputs(process_config, controllable_outputs, target_values):
    """
    Simulates the logic of _merge_controllable_inputs.

    NEW BEHAVIOR: Policy outputs ONLY controllable inputs, which are merged
    with non-controllable values from target.

    Args:
        process_config: Process configuration
        controllable_outputs: Dict of {controllable_input_name: policy_value}
        target_values: Dict of {input_name: target_value}

    Returns:
        Dict of final values after merging
    """
    info = get_controllable_info(process_config)
    input_labels = process_config['input_labels']

    final_values = {}

    # Place controllable outputs from policy
    for label in info['controllable_labels']:
        final_values[label] = controllable_outputs[label]

    # Place non-controllable values from target
    for label in info['non_controllable_labels']:
        final_values[label] = target_values[label]

    return final_values


def test_microetch_scenario():
    """Test the microetch scenario where Temperature is non-controllable."""

    print("="*70)
    print("TEST: Microetch Process (Temperature non-controllable)")
    print("="*70)

    microetch_config = next(p for p in PROCESSES if p['name'] == 'microetch')
    info = get_controllable_info(microetch_config)

    print(f"\nProcess info:")
    print(f"  Controllable: {info['controllable_labels']} (indices: {info['controllable_indices']})")
    print(f"  Non-controllable: {info['non_controllable_labels']} (indices: {info['non_controllable_indices']})")
    print(f"  Policy output dim: {info['n_controllable']} (not {len(microetch_config['input_labels'])})")

    # Target scenario values
    target_values = {
        'Temperature': 300.0,
        'Concentration': 1.5,
        'Duration': 60.0
    }

    # Policy generator outputs ONLY controllable inputs
    # (Temperature is NOT generated by the policy at all)
    controllable_outputs = {
        'Concentration': 2.0,
        'Duration': 75.0
    }

    # Merge controllable outputs with non-controllable from target
    final_inputs = simulate_merge_controllable_inputs(
        microetch_config, controllable_outputs, target_values
    )

    print(f"\nTarget values:           {target_values}")
    print(f"Policy outputs (controllable only): {controllable_outputs}")
    print(f"Final inputs (merged):   {final_inputs}")

    # Verify
    assert final_inputs['Temperature'] == 300.0, "Temperature should be from target"
    assert final_inputs['Concentration'] == 2.0, "Concentration should be from policy"
    assert final_inputs['Duration'] == 75.0, "Duration should be from policy"

    print("\n✓ TEST PASSED: Merge logic works correctly!")

    print("\nKey difference from old behavior:")
    print("  OLD: Policy generated Temperature=310.0, then it was overwritten with 300.0")
    print("  NEW: Policy only generates Concentration and Duration, Temperature comes from target")


def test_plasma_scenario():
    """Test the plasma process where Duration is non-controllable."""

    print("\n" + "="*70)
    print("TEST: Plasma Process (Duration non-controllable)")
    print("="*70)

    plasma_config = next(p for p in PROCESSES if p['name'] == 'plasma')
    info = get_controllable_info(plasma_config)

    print(f"\nProcess info:")
    print(f"  Controllable: {info['controllable_labels']} (indices: {info['controllable_indices']})")
    print(f"  Non-controllable: {info['non_controllable_labels']} (indices: {info['non_controllable_indices']})")
    print(f"  Policy output dim: {info['n_controllable']}")

    target_values = {
        'RF_Power': 100.0,
        'Duration': 30.0
    }

    # Policy outputs ONLY RF_Power
    controllable_outputs = {
        'RF_Power': 120.0
    }

    final_inputs = simulate_merge_controllable_inputs(
        plasma_config, controllable_outputs, target_values
    )

    print(f"\nTarget values:           {target_values}")
    print(f"Policy outputs (controllable only): {controllable_outputs}")
    print(f"Final inputs (merged):   {final_inputs}")

    assert final_inputs['RF_Power'] == 120.0, "RF_Power should be from policy"
    assert final_inputs['Duration'] == 30.0, "Duration should be from target"

    print("\n✓ TEST PASSED: Plasma merge works correctly!")


def test_galvanic_scenario():
    """Test galvanic process where all inputs are controllable."""

    print("\n" + "="*70)
    print("TEST: Galvanic Process (All inputs controllable)")
    print("="*70)

    galvanic_config = next(p for p in PROCESSES if p['name'] == 'galvanic')
    info = get_controllable_info(galvanic_config)

    print(f"\nProcess info:")
    print(f"  Controllable: {info['controllable_labels']} (indices: {info['controllable_indices']})")
    print(f"  Non-controllable: {info['non_controllable_labels']} (none)")
    print(f"  Policy output dim: {info['n_controllable']} (full input dim)")

    target_values = {
        'CurrentDensity': 50.0,
        'Duration': 120.0
    }

    # Policy outputs ALL inputs (since all are controllable)
    controllable_outputs = {
        'CurrentDensity': 55.0,
        'Duration': 130.0
    }

    final_inputs = simulate_merge_controllable_inputs(
        galvanic_config, controllable_outputs, target_values
    )

    print(f"\nTarget values:           {target_values}")
    print(f"Policy outputs (all controllable): {controllable_outputs}")
    print(f"Final inputs (no merge needed): {final_inputs}")

    assert final_inputs['CurrentDensity'] == 55.0, "CurrentDensity should be from policy"
    assert final_inputs['Duration'] == 130.0, "Duration should be from policy"

    print("\n✓ TEST PASSED: All inputs from policy (no merge needed)!")


def test_policy_output_dimensions():
    """Test that policy output dimensions are correctly calculated."""

    print("\n" + "="*70)
    print("TEST: Policy Output Dimensions")
    print("="*70)

    for process in PROCESSES:
        info = get_controllable_info(process)
        full_dim = len(process['input_labels'])
        controllable_dim = info['n_controllable']

        print(f"\n{process['name']}:")
        print(f"  Full input dim: {full_dim}")
        print(f"  Policy output dim: {controllable_dim}")
        print(f"  Reduction: {full_dim - controllable_dim} dimensions saved")

        # Verify dimensions match
        assert controllable_dim == len(info['controllable_labels'])
        assert controllable_dim + info['n_non_controllable'] == full_dim

    print("\n✓ TEST PASSED: All dimensions correctly calculated!")


if __name__ == '__main__':
    print("\n" + "="*70)
    print("TESTING NEW CONTROLLABLE INPUTS LOGIC")
    print("Policy generators output ONLY controllable inputs")
    print("="*70)

    test_microetch_scenario()
    test_plasma_scenario()
    test_galvanic_scenario()
    test_policy_output_dimensions()

    print("\n" + "="*70)
    print("ALL TESTS PASSED ✓")
    print("="*70)
