"""
Configuration for CasualiT surrogate training.

This trains a model to predict reliability F from process trajectories.
The model learns to map:
    X (trajectory: inputs + outputs for each process) -> Y (reliability F)

Data Generation:
- Trajectories can be generated live using ProcessChain (use_existing_dataset=False)
- Or loaded from full_trajectories.pt generated by generate_dataset.py (use_existing_dataset=True)
- F is computed using the mathematical formula (ProTSurrogate / ReliabilityFunction)

Model Architecture:
- 'proT': SimpleSurrogateModel (transformer encoder, sequence-to-scalar)
- 'StageCausaliT': StageCausalForecaster (dual decoder: S->X, X->Y)
- 'SingleCausalLayer': SingleCausalForecaster (single decoder: S->X)
"""

SURROGATE_CONFIG = {
    # Data generation (minimal for pipeline testing)
    'data': {
        # If True: load pre-existing full_trajectories.pt (from generate_dataset.py)
        # If False: generate data from ProcessChain live (original behaviour)
        'use_existing_dataset': True,

        # Path to the dataset generated by generate_dataset.py
        # Used only when use_existing_dataset = True
        'dataset_path': 'data/trajectories/full_trajectories.pt',

        # Split fractions for the existing dataset
        'train_frac': 0.70,
        'val_frac': 0.15,
        'test_frac': 0.15,

        # Parameters below are used only when use_existing_dataset = False
        'n_trajectories': 200,         # Minimal for pipeline test
        'n_val_trajectories': 50,      # Minimal validation
        'n_test_trajectories': 50,     # Minimal test
        'batch_size_generation': 200,  # Generate all in one batch
        'random_seed': 42,

        # Scenario diversity
        'n_scenarios': 2,              # Just 2 scenarios for speed
        'scenario_seed_offset': 1000,

        # Process selection
        'process_names': [None],  # Use all processes
    },

    # Model architecture
    'model': {
        # Which CausalIT architecture to use as surrogate.
        # Values: 'proT', 'StageCausaliT', 'SingleCausalLayer'
        'casualit_model': 'proT',
        'd_model_enc': 64,
        'd_model_dec': 64,
        'd_ff': 128,
        'd_qk': 32,

        'e_layers': 3,
        'd_layers': 2,
        'n_heads': 4,

        'dropout_emb': 0.2,
        'dropout_attn_out': 0.2,
        'dropout_ff': 0.2,

        'activation': 'gelu',
        'norm': 'batch',
        'use_final_norm': True,
    },

    # Training
    'training': {
        'max_epochs': 300,
        'batch_size': 32,
        'learning_rate': 3e-4,
        'weight_decay': 0.03,
        'loss_fn': 'mse',
        'k_fold': 1,
        'seed': 42,
        'patience': 40,

        'use_scheduler': True,
        'scheduler_factor': 0.5,
        'scheduler_patience': 15,

        'loss_weight_x': 0.3,
        'loss_weight_y': 1.0,

        'entropy_regularizer': False,
        'gamma': 0.05,
    },

    # Checkpoints
    'checkpoints': {
        'save_dir': 'causaliT/checkpoints/surrogate',
        'save_every_n_epochs': 50,
        'keep_top_k': 3,               # Keep top k checkpoints
    },

    # Report
    'report': {
        'generate_pdf': True,
        'output_dir': 'causaliT/reports/surrogate',
        'include_plots': True,
        'plot_dpi': 150,
    },

    # Logging
    'logging': {
        'log_every_n_steps': 10,
        'verbose': True,
    },
}
